config/routes.rb
Rails.application.routes.draw do

  root 'pages#new'
  get 'new_request' => 'pages#new_request'

end

app/models/history.rb
class History < ActiveRecord::Base
	attr_accessor :name :email :phone :address :status

	def create

		@History = History.new

	end	


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testproject2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Accent</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        
          <li> <%= link_to 'Home', root_path %></li>
          <li> <%= link_to 'New Request', new_request_path %></li>



  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



   <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>
    <%= yield %>
   
  

</body>
</html>

app/views/pages/new.html.erb
<div class="container center">


<h1> Start Using Tomorrow's Technology</h1>


<br>
</br>
	 <form class="form-inline" role="form">
            <div class="form-group">
              <input type="tel" class="form-control" id="search" placeholder="Enter Mobile Number">
            </div>
            <button type="submit" class="btn btn-default btn-lg">Continue ></button>
          </form>          

</div>

app/views/pages/new_request.html.erb
<%= form_for :history do |f| %>
  Name: <%= f.text_field :name %><br/>
  Email: <%= f.text_field :email %><br/>
  Phone: <%= f.text_field :phone %><br/>
  Address: <%= f.text_area :address %><br/>
  <%= f.submit %>
<% end %>

app/views/pages/queue.html.erb
<h2> My SMS dashboard to receive messages </h2>

app/views/pages/service_history.html.erb
service_history.html.erb

app/views/pages/sms.html.erb
<h2> My SMS dashboard to receive messages </h2>